services:
  nginx:
    build:
      context: ./docker/nginx
    container_name: dog-care-api-nginx
    depends_on:
      - php
    environment:
      HOST: localhost
      PORT: ${APP_PORT:-80}:80
      PHP_HOST: dog-care-api-php
      PHP_PORT: 9000
    ports:
      - ${APP_PORT:-80}:80
  php:
    build:
      context: docker/php
      args:
        USER_NAME: ${USER_NAME:-user}
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: dog-care-api-php
    depends_on:
      - mysql
    environment:
      XDEBUG_CLIENT_HOST: ${XDEBUG_CLIENT_HOST:-host.docker.internal}
      XDEBUG_CLIENT_PORT: ${XDEBUG_CLIENT_PORT:-9003}
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG:-serverName=Docker}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - '9000:9000'
    volumes:
      - '.:/var/www/html'
  mysql:
    container_name: dog-care-api-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-dog-care-api}
      MYSQL_DATABASE: ${DB_NAME:-dog-care-api}
      MYSQL_USER: ${DB_USER:-dog-care-api}
      MYSQL_PASSWORD: ${DB_PASSWORD:-dog-care-api}
    image: mysql:8.2.0
    ports:
      - ${DB_PORT:-3306}:3306
    volumes:
      - dog-care-api-db:/var/lib/mysql
volumes:
  dog-care-api-db: