allergy:
    resource: allergy/allergy-routes.yaml

client:
    resource: client/client-routes.yaml

disease:
    resource: disease/disease-routes.yaml

medicine:
    resource: medicine/medicine-routes.yaml
