post-allergy:
  controller: \App\Controller\Allergy\PostAllergyController
  methods: POST
  path: /allergies/{id}
  requirements:
    id: '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'

put-allergy:
  controller: \App\Controller\Allergy\PutAllergyController
  methods: PUT
  path: /allergies/{id}
  requirements:
    id: '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'

delete-allergy:
  controller: \App\Controller\Allergy\DeleteAllergyController
  methods: DELETE
  path: /allergies/{id}
  requirements:
    id: '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'

get-allergy:
  controller: \App\Controller\Allergy\GetAllergyController
  methods: GET
  path: /allergies/{id}
  requirements:
    id: "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"

get-allergies:
  controller: \App\Controller\Allergy\GetAllergiesController
  methods: GET
  path: /allergies
