post-client:
  controller: \App\Controller\Client\PostClientController
  methods: POST
  path: /clients/{id}
  requirements:
    id: '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'

put-client:
  controller: \App\Controller\Client\PutClientController
  methods: PUT
  path: /clients/{id}
  requirements:
    id: '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'

delete-client:
  controller: \App\Controller\Client\DeleteClientController
  methods: DELETE
  path: /clients/{id}
  requirements:
    id: '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'

get-client:
  controller: \App\Controller\Client\GetClientController
  methods: GET
  path: /clients/{id}
  requirements:
    id: "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"

get-clients:
  controller: \App\Controller\Client\GetClientsController
  methods: GET
  path: /clients
